import { chromium } from 'playwright';import fs from 'node:fs/promises';import path from 'node:path';
const PAGE=process.env.MVR_ACCIDENTS_PAGE||'https://www.mvr.bg/map/apps/dashboards/0b7065b1f1d34d7d8ad530c51434a9f0';const OUTPUT=path.resolve(process.env.BGTRAFFIC_ACCIDENTS_OUTPUT||'collector-output/accidents.json');const DIAG=path.resolve('collector-diagnostics');
const records=new Map(),services=new Set(),matched=[];
const clean=v=>String(v??'').replace(/<[^>]+>/g,' ').replace(/\s+/g,' ').trim();const pick=(o,keys)=>{if(!o||typeof o!=='object')return null;for(const k of keys){const a=Object.keys(o).find(x=>x.toLowerCase()===k.toLowerCase()||x.toLowerCase().includes(k.toLowerCase()));if(a&&o[a]!==''&&o[a]!=null)return o[a]}return null};const num=v=>{const n=Number(String(v??'').replace(',','.'));return Number.isFinite(n)?n:null};
function merc(x,y){const lng=x/20037508.34*180;let lat=y/20037508.34*180;lat=180/Math.PI*(2*Math.atan(Math.exp(lat*Math.PI/180))-Math.PI/2);return [lat,lng]}
function coords(g){if(!g)return [null,null];let x=num(g.x??g.longitude),y=num(g.y??g.latitude);if(x==null||y==null)return [null,null];if(Math.abs(x)>180||Math.abs(y)>90)return merc(x,y);return [y,x]}
function dateValue(v){if(v==null||v==='')return null;if(typeof v==='number'||/^\d{10,13}$/.test(String(v))){let n=Number(v);if(n<2e10)n*=1000;return new Date(n).toISOString()}const d=new Date(v);return Number.isNaN(d.getTime())?null:d.toISOString()}
function normalize(f){const a=f?.attributes??f?.properties??f;if(!a||typeof a!=='object')return null;const [lat,lng]=coords(f.geometry??a.geometry);if(lat==null||lng==null||lat<40||lat>45||lng<20||lng>30)return null;const keys=Object.keys(a).join(' ').toLowerCase();if(!/птп|произш|катастроф|accident|injur|ранен|загин|fatal|вид/.test(keys))return null;
 const occurred=dateValue(pick(a,['occurred_at','datetime','date_time','data_chas','date','дата','час']))||new Date().toISOString();const id=clean(pick(a,['globalid','objectid','id','ptp_id','номер'])??`${occurred}|${lat}|${lng}`);const injured=Math.max(0,Math.round(num(pick(a,['injured','raneni','ранени','пострадали']))||0));const fatalities=Math.max(0,Math.round(num(pick(a,['fatalities','killed','zaginali','загинали']))||0));const location=clean(pick(a,['location','address','mesto','населено','община','област'])??'Неуточнено място');const severity=clean(pick(a,['severity','vid_ptp','type','вид птп','категория'])??(fatalities?'Със загинали':injured?'С ранени':'ПТП'));const road=clean(pick(a,['road','pat','път','номер на пътя'])??'');const description=clean(pick(a,['description','opisanie','описание','circumstances'])??'');return {external_id:id,occurred_at:occurred,latitude:lat,longitude:lng,location,severity,injured,fatalities,road_code:road,description};}
function walk(v,depth=0,seen=new WeakSet()){if(depth>14||v==null||typeof v!=='object'||seen.has(v))return;seen.add(v);if(Array.isArray(v)){for(const x of v)walk(x,depth+1,seen);return}if(Array.isArray(v.features)){for(const f of v.features){const n=normalize(f);if(n)records.set(n.external_id,n)}}for(const x of Object.values(v))walk(x,depth+1,seen)}
function parse(t){try{walk(JSON.parse(t))}catch{}}
await fs.mkdir(DIAG,{recursive:true});const browser=await chromium.launch({headless:true});const context=await browser.newContext({locale:'bg-BG',timezoneId:'Europe/Sofia',viewport:{width:1440,height:1000}});
context.on('response',async r=>{const u=r.url();if(/\/(FeatureServer|MapServer)\/\d+\/query/i.test(u))services.add(u.split('/query')[0]);const ct=(await r.headerValue('content-type'))||'';if(r.status()<200||r.status()>=400||(!/json|text/i.test(ct)&&!/query|FeatureServer|MapServer/i.test(u)))return;try{const b=await r.body();if(b.length>40e6)return;const before=records.size;parse(b.toString('utf8'));if(records.size>before)matched.push({url:u,added:records.size-before})}catch{}});
const page=await context.newPage();let err='';try{await page.goto(PAGE,{waitUntil:'domcontentloaded',timeout:120000});await page.waitForTimeout(45000);await page.screenshot({path:path.join(DIAG,'mvr-accidents.png'),fullPage:true})}catch(e){err=String(e?.message||e)}
for(const service of [...services].slice(0,20)){for(let offset=0;offset<10000;offset+=2000){try{const url=service+'/query?where=1%3D1&outFields=*&returnGeometry=true&f=json&resultOffset='+offset+'&resultRecordCount=2000';const r=await context.request.get(url,{timeout:60000});if(!r.ok())break;const j=await r.json();const before=records.size;walk(j);if(!j.features?.length||j.features.length<2000)break;if(records.size===before&&offset>0)break}catch{break}}}
const list=[...records.values()].sort((a,b)=>Date.parse(b.occurred_at)-Date.parse(a.occurred_at));if(!list.length){await browser.close();throw new Error('Не са разпознати ПТП от картата на МВР.');}const payload={source:'mvr_accidents',schema_version:1,collector_version:'2.0.0',collected_at:new Date().toISOString(),official_page:PAGE,captured_from:matched[0]?.url||PAGE,records:list,diagnostics:{services:[...services],matched_responses:matched.slice(0,20),page_error:err}};await fs.mkdir(path.dirname(OUTPUT),{recursive:true});await fs.writeFile(OUTPUT,JSON.stringify(payload,null,2));await browser.close();console.log(`accident records: ${list.length}`);
